Scrum 7 ratings and reviews for credibility
Parkit-Place/Parkit-Place pull request #13
Opened 2024-11-14 00:45 UTC by wu103-mcmaster

- added credibility stars and score accumulations
- added number of reviews corresponding to added credibility scores when accumulating
- all CRUD functionality should be present and buttons with fields to test credibility are available
- added a profile page for user specific information, currently all testing buttons and stars/scores/reviews there
- you can head there from localhost:port\ProfilePage to see it there

2024-11-14 00:48 UTC, wu103-mcmaster commented on frontend/web/park-it-place/src/pages/Home.js
> +      {/* <p>User: {currentUser?.email}</p> */}
I can't remember why I had commented this out or for what I was testing, but I think its fine. If anyone is going to actively use it they can uncomment it again, or the next PR made can change it back accordingly. I just caught this now and cannot be bothered to re-push LOL.

2024-11-14 01:52 UTC, Ivan-ebos commented on frontend/web/park-it-place/src/components/CredibilityScore.js
> +            {credibilityRating !== null && (
"credibilityRating" will work the same as "credibilityRating !== null"

2024-11-14 01:52 UTC, Ivan-ebos commented on frontend/web/park-it-place/src/components/CredibilityScore.js
> +            <div style={{ display: "flex", alignItems: "center", fontSize: "20px" }}>
Can we use tailwind for styling

2024-11-14 01:57 UTC, Ivan-ebos commented on frontend/web/park-it-place/src/components/CredibilityScore.js
> +                {`
If we are adding custom font it should be added in index.css

2024-11-14 01:58 UTC, Ivan-ebos commented on frontend/web/park-it-place/src/components/CredibilityScore.js
> +    const renderStarRating = (score, reviews) => {
Im tempted to say renderStartRating should be its own component

2024-11-14 01:59 UTC, Ivan-ebos reviewed
Hey, I commented a couple things in the code.

2024-11-14 02:26 UTC, AvinLT requested changes

2024-11-14 02:26 UTC, AvinLT commented on frontend/web/park-it-place/src/firebase/firebase.js
> +import { getFirestore } from "firebase/firestore";
importing getFirestore again here, gives you a compile error on FE since its already imported on line 2. You can try compile FE on master branch with your 3 commits cherry-picked on top to simulate what merging the PR would do

2024-11-14 21:49 UTC, wu103-mcmaster commented on frontend/web/park-it-place/src/components/CredibilityScore.js
> +                {`
will fix this later when we figure out how to call our index.css tailwind font family stuff

2024-11-14 21:51 UTC, wu103-mcmaster commented on frontend/web/park-it-place/src/components/CredibilityScore.js
> +            {credibilityRating !== null && (
fixed

2024-11-14 21:51 UTC, wu103-mcmaster commented on frontend/web/park-it-place/src/firebase/firebase.js
> +import { getFirestore } from "firebase/firestore";
fixed

2024-11-15 19:28 UTC, Ivan-ebos approved these changes

2024-11-16 06:44 UTC, AvinLT approved these changes

2024-11-16 06:44 UTC, merged